# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFramework

  pod 'PhysData', :git => 'git@gitlab.com:wondercise_sys/wondercise-ios-phys-data.git', :branch => 'master'
  pod 'FitnessDevice', :git => 'git@gitlab.com:wondercise_sys/wondercise-ios-fitness-device.git', :branch => 'master'


end
